<?php

/**
 * @file
 * Logs HTTP module.
 */

use GuzzleHttp\Exception\RequestException;
use Drupal\Core\Utility\Error;

/**
 * Provides custom PHP exception handling.
 *
 * Uncaught exceptions are those not enclosed in a try/catch block. They are
 * always fatal: the execution of the script will stop as soon as the exception
 * handler exits.
 *
 * @param $exception
 *   The exception object that was thrown.
 *
 * @see _drupal_exception_handler()
 */
function _logs_http_exception_handler($exception) {
  require_once DRUPAL_ROOT . '/core/includes/errors.inc';

  try {
    // Log the message to the watchdog and return an error page to the user.
    _drupal_log_error(Error::decodeException($exception), TRUE);
  }
  // PHP 7 introduces Throwable, which covers both Error and
  // Exception throwables.
  catch (\Throwable $error) {
    _drupal_exception_handler_additional($exception, $error);
  }
}

/**
 * Runs on shutdown to clean up and display developer information.
 *
 * LogsHttpEventSubscriber registers this function as a shutdown function.
 */
function logs_http_shutdown() {
  /** @var \Drupal\logs_http\Logger\LogsHttpLogger $logs_http_logger */
  $logs_http_logger = \Drupal::service('logs_http.logs_http_logger');
  if (!$logs_http_logger->isEnabled()) {
    return;
  }

  if (!$events = $logs_http_logger->getEvents()) {
    return;
  }

  $url = $logs_http_logger->getUrl();

  // Send events to logs.
  foreach ($events as $event) {
    $client = \Drupal::httpClient();

    try {
      // Send data to Logs.
      $client->post($url, ['json' => $event]);
    }
    catch (RequestException $e) {

    }
  }
}
