<?php

/**
 * @file
 * Logs HTTP module.
 */

use GuzzleHttp\Exception\RequestException;

/**
 * Runs on shutdown to clean up and display developer information.
 *
 * @see \Drupal\logs_http\EventSubscriber\LogsHttpEventSubscriber
 */
function logs_http_shutdown() {
  /** @var \Drupal\logs_http\Logger\LogsHttpLogger $logs_http_logger */
  $logs_http_logger = \Drupal::service('logs_http.logs_http_logger');
  if (!$logs_http_logger->isEnabled()) {
    return;
  }

  if (!$events = $logs_http_logger->getEvents()) {
    return;
  }

  $url = $logs_http_logger->getUrl();

  // Send events to logs.
  foreach ($events as $event) {
    $client = \Drupal::httpClient();

    try {
      // Send data to Logs.
      $client->post($url, ['json' => $event]);
    }
    catch (RequestException $e) {

    }
  }
}
